    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          # Checking out
          - uses: actions/checkout@v1

          # Setting up JDK
          - name: set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8

          # Gradle build
          - name: Build with Gradle
            run: ./gradlew build

          # Archiving code coverage results ←このセクションがテスト結果を保存している
          - name: Archive code coverage results
            if: always()
            uses: actions/upload-artifact@v1
            with:
              name: code-coverage-report
              path: app/build/reports/tests/testDebugUnitTest
